language: c

compiler:
  - gcc

cache:
  - apt

env:
  global:
    - CFLAGS="-fPIC -O0 -ggdb -fno-inline -fno-omit-frame-pointer"

notifications:
  email:
    recipients:
      - christian@hergert.me

    on_success: change
    on_failure: always

before_install:
  - sudo apt-get update
  - sudo apt-get install libglib2.0-dev libgirepository1.0-dev

install:
  NOCONFIGURE=1 ./autogen.sh
  ./configure --prefix=~/.local
  make -j4
  make distcheck -j4
